version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
    - ${DOCKER_WEBSERVER_PORT:-80}:80
    volumes:
    - ./:/var/www/

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mh_app_db
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASS:-root}
    volumes:
    - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
    - ${DOCKER_PMA_PORT:-8185}:80

volumes:
  mysql_data:
